"""

Filename: Function.py
Developer: Leandro Fernandes
Date: 22/08/2024
Description: O código consiste em varias funções para formatar arquivos Excel com suas colunas específicas.

Chaves para pesquisa:

- Função para excluir as colunas do arquivo contendo os itens em box ==> RemoveColumnsBox

- Função para excluir as colunas do arquivo contendo os itens em I2 ==> RemoveColumnsI2

- Função para excluir as colunas do arquivo contendo os itens em locações virtuais ==> RemoveColumnsVirtualLoc

- Função para excluir as colunas do arquivo contendo os itens com missões pendentes de confirmação ==> RemoveColumnsMissions

- Função para excluir as colunas do arquivo contendo os itens com pendência de armazenamento ==> RemoveColumnsStorage

- Função para excluir as colunas do arquivo contendo os itens sistemicamente parados em qualidade ==> RemoveColumnsQuality

- Função para excluir as colunas do arquivo contendo os itens que foram feitos retorno de linha ==> RemoveColumnsRTL

- Função para excluir as colunas do arquivo contendo os itens alocados em Shuttle_load_cl ==> RemoveColumnsSHTLoad

- Função para excluir as colunas do arquivo contendo os itens alocados em Shuttle_trs_pc ==> RemoveColumnsTRS

- Função para excluir as colunas do arquivo contendo os itens que não foram transferidos para UDC container ==> RemoveColumnsContainer

- Função para excluir as colunas do arquivo contendo os itens rejeitados ==> RemoveColumnsRej


"""

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

import pandas as pd

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


# Função para excluir colunas indesejadas de um DataFrame
def RemoveColumnsBox(file_path):
    columns_to_remove = [
        "Compartimento",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "UdC Container",
        "Destino",
        "Usuario Modificação",
        "Status Contábil",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Origem",
        "Site",
        "Documento Click",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Data FIFO",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Inserção",
        "Update",
    ]

    # Ler o arquivo CSV
    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    # Remover as colunas indesejadas
    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsI2(file_path):
    columns_to_remove = [
        "Compartimento",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "UdC Container",
        "Destino",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Site",
        "Documento Click",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Data FIFO",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Inserção",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsVirtualLoc(file_path):
    columns_to_remove = [
        "Compartimento",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "UdC Container",
        "Status Contábil",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Site",
        "Documento Click",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Data FIFO",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Inserção",
        "RC",
        "Nota Fiscal",
        "Código Fornecedor",
        "Razão Social Fornecedor",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsMissions(file_path):
    columns_to_remove = [
        "Compartimento",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Usuario Modificação",
        "Data Carga",
        "Origem",
        "Inserção",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Documento Click",
        "RC",
        "Nota Fiscal",
        "Código Fornecedor",
        "Razão Social Fornecedor",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Data FIFO",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsStorage(file_path):
    columns_to_remove = [
        "Compartimento",
        "Data Carga",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "UdC Container",
        "Destino",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Origem",
        "Site",
        "Documento Click",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Data FIFO",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsQuality(file_path):
    columns_to_remove = [
        "Compartimento",
        "Nota Fiscal",
        "Usuario Modificação",
        "Área",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "UdC Container",
        "Destino",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Origem",
        "Documento Click",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Data FIFO",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Inserção",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsRTL(file_path):
    columns_to_remove = [
        "Compartimento",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "UdC Container",
        "Destino",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Origem",
        "Site",
        "Documento Click",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Data FIFO",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Data Carga",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsSHTLoad(file_path):
    columns_to_remove = [
        "Compartimento",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "UdC Container",
        "Destino",
        "Status Contábil",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Origem",
        "Site",
        "Documento Click",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Data FIFO",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Inserção",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsTRS(file_path):
    columns_to_remove = [
        "Compartimento",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "UdC Container",
        "Destino",
        "Status Contábil",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Origem",
        "Site",
        "Documento Click",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Data FIFO",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Inserção",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsContainer(file_path):
    columns_to_remove = [
        "Compartimento",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Origem",
        "Inserção",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Documento Click",
        "RC",
        "Nota Fiscal",
        "Código Fornecedor",
        "Razão Social Fornecedor",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Data FIFO",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


def RemoveColumnsRej(file_path):
    columns_to_remove = [
        "Compartimento",
        "Etiqueta de Expedição",
        "UdC Temporária",
        "Origem",
        "Inserção",
        "Obsoleto",
        "Overstock",
        "Versão",
        "Lote",
        "Status Estoque",
        "Causal Bloqueio",
        "Reservada",
        "Quantidade Alocada",
        "Quantidade Entrada",
        "Quantidade Verificada",
        "Quantidade Urgente",
        "Urgente",
        "Área",
        "Documento Click",
        "RC",
        "Nota Fiscal",
        "Código Fornecedor",
        "Razão Social Fornecedor",
        "Linha NFe Entrada",
        "Volume NFe Entrada",
        "Compartimento.1",
        "Causal",
        "Nº NFe",
        "Linha NFe",
        "Data NFe",
        "Tipo Proprietário Estoque",
        "Fornecedor",
        "Fornecedor Tipo",
        "[ProduçãonData]",
        "Data Aviso",
        "Data Validade",
        "Data FIFO",
        "Pedido Número",
        "Tipo Pedido",
        "[Linha Pedido]",
        "Expedição",
        "Número Viagem",
        "Cliente Reserva",
        "Tipo Cliente Reserva",
        "Reserva Documento",
        "Ciclo de Coleta",
        "Batch de Coleta",
        "Agregação",
        "Packaging Batch",
        "Unnamed: 58",
        "Tipo Confecção",
        "Tipo Embalagem",
        "Quantidade por SingleBox",
        "Confecções x Embalagem",
        "Classe Sazonamento",
        "Fase",
        "Stagionatura Ativa",
        "Anomalia",
        "Data Termino fase",
        "Número Inventário",
        "A Contar",
        "State",
        "(Fl_inventariato)",
        "(Cd_blocco_prec)",
        "Stamp",
        "Disponibilidade",
        "Classe Estoque 1",
        "Stock Detail Classe 2",
        "Stock Detail Classe 3",
        "Stock Detail Classe 4",
        "Stock Detail Classe 5",
        "Classe Estoque 6",
        "(Df_note_assegnamento)",
        "Primeira Coordenada do Produto",
        "Segunda Coordenada do Produto",
        "Terceira Coordenada do Produto",
        "Quarta Coordenada do Produto",
        "Quinta Coordenada do Produto",
        "Sexta Coordenada do Produto",
        "Sétima Coordenada do Produto",
        "Oitava Coordenada do Produto",
        "Nona Coordenada do Produto",
        "Décima Coordenada do Produto",
        "Nota",
        "Classe Estoque 1.1",
        "Stock Detail Classe 2.1",
        "Stock Detail Classe 3.1",
        "Stock Detail Classe 4.1",
        "Estoque Classe Número 2",
        "Estoque Classe Número 3",
        "Estoque Classe Número 5",
        "Estoque Classe Número 6",
        "Estoque Classe Número 4",
        "Estoque Classe Flag 2",
        "Estoque Classe Flag 3",
        "Estoque Classe Flag 5",
        "Estoque Classe Flag 6",
        "Estoque Classe Dt 1",
        "Estoque Classe Dt 2",
        "Estoque Classe Dt 3",
        "Estoque Classe Dt 4",
        "Estoque Classe Dt 5",
        "Estoque Classe Df 1",
        "Estoque Classe Df 2",
        "Estoque Classe Df 3",
        "Estoque Classe Df 4",
        "Estoque Classe Df 5",
        "Estoque Classe Df 5.1",
        "Matrícula",
        "(Unpackstamp)",
        "Período",
        "Qtde.Trabalhada",
        "Tipo de Site",
        "Depositante",
        "(Qt_scaricata)",
        "Proprietário Estoque",
        "Dat Desbloqueio",
        "(Dt_ultimo_movimento)",
        "Last SellDate",
        "Etiqueta",
        "Destino",
        "Site",
        "Usuario Modificação",
    ]

    data_frame = pd.read_csv(file_path, sep=";", low_memory=False)

    data_frame = data_frame.drop(columns_to_remove, axis=1)

    return data_frame
